spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: admin
      username: root
      password: root
  shell:
    interactive:
      enabled: true

  batch:
    jdbc:
      initialize-schema: always
  flyway:
    enabled: true
    locations: classpath:db/migration

    command:
      version:
        enabled: false

  datasource:
    url: jdbc:h2:mem:maindb

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none

    show-sql: true